### ISSUE TITLE
Can't work out where to set the PATH.

### ISSUE THREAD

**Issue by LamboCreeper** [foreshadow/atom-python-run#18]
Hey, 

I don't want to sound like an idiot, but where exactly to I put the path to Python Launcher. Also, will this still work even though i'm using macOS?

_Thanks,
**Lambo**._

**Comment by foreshadow** [comment]
Hello @LamboCreeper,

You mentioned

> Add the directory of python.exe to `PATH`.

This means it is required set the environment variable `path` to 
`%path%;<the directory that python.exe is in>`, 
because this package uses just a simple command `python.exe` without absolute path in cmd, which I cannot predict where it is in exactly.

However, as I have reminded in [readme.md](https://github.com/foreshadow/atom-python-run/blob/master/README.md#prerequisite), the prerequisite of this package is Windows operating system.
This is not pure JavaScript package. I suppose that environment variable and especially cmd are typically windows's feature, and another C-language program(compiled with g++, using a extra .dll file) is used to support this package. So it may not work in Mac OS.

As a Windows user, I do not have a Mac OS to develop and test this package, and I am not familiar with Mac OS applications developing, so I am sorry to tell you this package can not support Mac OS or operation systems other than Windows currently.

If you are interested, you can join to develop the Mac OS version of this package.

Thank you for your attention.

**Infinity**

**Comment by xovertheyearsx** [comment]
**How to Add Python to your `PATH` Environment Variable**

1. `ctrl + r` to open `run` command prompt
2. type in `control panel` and hit `enter` or click `ok`
3. click `systems and security`
4. click `system`
5. click `advanced system settings`
6. click `environment variables`
7. under `system variable`, select the `Path` variable.
8. click edit under `system variables`
9. click `new`, and add the path to the `python.exe`.
10. click `new`, and add the `scripts` path as well.

Mac OS X and Linux come preinstalled with `python` and are already a part of the `PATH` Environment Variable. As of version `0.8.0`, `atom-python-run` is now cross-platform.
