### ISSUE TITLE
Suggestions for additional features

### ISSUE THREAD

**Issue by DamSenViet** [foreshadow/atom-python-run#24]
I was thinking maybe we could keep running code in the python shell after the script has been run. So for example let's say I have a couple of definitions I want to work with inside the python script, and let's say that it's a nested dictionary object loaded from json text. I think I would want to be able to continue interacting with the shell to continue navigating through my own code and testing it.
For example:
The python script:
  the_json = dict
The shell:
  the_json[key][key][key][key][some index #][key][key]
  *error message or object being returned*

And maybe instead of ending the shell right away, we could exit the shell through the ESC key or ctrl+w  would be nice.

**Comment by foreshadow** [comment]
Good idea. Try to use the command `python -i  {file}` in settings.

**Comment by HiImAndy** [comment]
I'm sort of new to programming, so I'm not exactly sure what you mean. Mind pointing me in the right direction here? LOL.

**Comment by foreshadow** [comment]
`python.exe`  provides a option `-i` to let it behave as you mentioned.
So it can be simply configured in
Atom - Settings(`ctrl+,`) - package - atom-python-run - Settings - Command of f6,
and change the value to `python -i {file}`.

**Comment by HiImAndy** [comment]
Is there a way to lock the commands to files with only the .py extension?

**Comment by foreshadow** [comment]
The current edition will only response to .py files.
See [atom-python-run.js Line 69~72](https://github.com/foreshadow/atom-python-run/blob/master/lib/atom-python-run.js#L69-L72)

**Comment by HiImAndy** [comment]
It's possible to bind the commands to the grammar scope in the keybindings. Any chance we could have the global keymap disabled?

**Comment by foreshadow** [comment]
I see what you mean. However, it may take some time for me to do it.

**Comment by xovertheyearsx** [comment]
This is great for small applications. As your code base grows in size and complexity, you should consider using TDD, or Test Driven Development, as you progress to automate the process of testing your code.

You can use `pytest` to start and migrate to using `unittest` as you become more comfortable with the testing approach. I recently dove head first in to `unittest` and its amazing. It saves so much time. 

A quick google search with the query **python unittest tutorial** should point you in the right direction. 

When you are ready to test your app by looking at edge cases through use of your app and are purposefully attempting to break things, thats when this module really shines. 

As foreshadow mentioned, you can accomplish this using `python -i {file}`. 

I'm fairly certain this may not work with the latest `cp` binary because it refuses to handle any arguments given to `python`. Although, it hasn't been made public, so I don't see this really being an issue. 

If the arguments fail, then at least you'll know why.

**Comment by foreshadow** [comment]
Extension filter is added in v0.8.1.
The matter of global keymap in still under consideration.
