### ISSUE TITLE
Output to a text file

### ISSUE THREAD

**Issue by IAmAFo0l** [foreshadow/atom-python-run#39]
As the command for F6, I put as:
python.exe "{file}" > output.txt
There is an **empty** text file "output.txt" created in the current directory. Output of the given input is displayed **right away** in the command prompt but not in the wanted file. Kindly tell me if I am missing something here.
Great work btw

**Comment by foreshadow** [comment]
In current version, the command `cmd /c start cp python {file} > output.txt` runs finally.
So the output of `cmd /c` (or `start`, not affecting `output.txt` to be empty) will be redirected to output.txt, which is empty, and `python {file}` runs seperately.

I tried several ways, and found that it seems the current version cannot do that for you. I feel sorry about that.

As a matter of fact, this is my first node.js project. I used too many wrappers to run this simple command. There are no surprises of all sorts of bugs or errors.
Thanks for your issue, and I see it. I am working on new versions and this problem could possibly be solved in next version.

**Comment by xovertheyearsx** [comment]
This was added in version 0.8.0.

Go to settings in Atom with `ctrl + ,`

In the left pane, where it says `Core`, `Editor`, etc... select `Packages`

Look for `atom-python-run` and click `Settings`

![atom-python-run-settings](https://user-images.githubusercontent.com/2978656/29051226-03bdcda8-7baf-11e7-9bbd-07766212c424.png)

Modify one of the default hotkeys (either F5 or F6).

from -> `Default: python {file}`

to -> `-p '/path/to/output/file.name' '>' python {file}`

and it should work.

The symbols for output are

- '>' stdout to truncated file.name
- '>>' append stdout to file.name
- '&>' stdout and stderr to truncated file.name

**Comment by foreshadow** [comment]
Actually I failed in testing this feature.
My commands: `-p 'output.txt' '>' python {file}`
It shows a messagebox saying something like  `Windows cannot find the file '-p'`
And cp.log does not change (or created if it doe not exists).

In the v0.8.0, I will get a better error (failed in cp/main.py) but it is not working still.

**Comment by xovertheyearsx** [comment]
it's still experimental. we'll figure it out. let me know if you come up with anything.

**Comment by foreshadow** [comment]
`Cannot find the file` is mainly because I checked `don't use cp`...
Maybe I can make it always call cp but select its behavior.
However, when I turned it off, it still fails...
I suppose the character `>` is parsed as a file redirection notation in `child_process.spawn` or `cmd /c`.
And if I replace the character `>` with a letter like `r`, it will be correctly passed into cp.
I offer a thinking that you can use `-p` for `>`, `-a` for `>>` and so on, instead of using `-p` + `>` / `>>` to distinguish them.
Moreover, I am thinking that if we don't use `start` or even `cmd /c start` we can direct the output just by the simplist `>` in command line, and `child_proces.spawn` has a option `shell` to open it with a window as I mentioned before.

Command = `-p 'output.txt' '>' python {file} `
cp.log = 
```
INFO: OS Type: win32
INFO: Version Info: v0.0.10
DEBUG: check_args(): index 0: arg: C:\Users\Infinity\.atom\packages\atom-python-run\cp\main.py
DEBUG: check_args(): index 1: arg: -p
DEBUG: check_args(): index 2: arg: 'output.txt'
DEBUG: check_args(): index 3: arg: '
DEBUG: check_args(): index 4: arg: python
DEBUG: check_args(): index 5: arg: C:\Users\Infinity\Desktop\hello.py
DEBUG: get_arg(): current argument: -p
DEBUG: shift(): index is now 1
DEBUG: get_arg(): current argument: 'output.txt'
DEBUG: shift(): index is now 2
DEBUG: get_arg(): current argument: '
ERROR: IndexError: invalid pipe symbol type: ['>', '>>', '&>', '&']
```

**Comment by xovertheyearsx** [comment]
something you should keep in mind is that when I made the -p (pipe) option, it was constructed to with `os.system` in mind; not `subprocess.call`.

`os.system` takes a single string, exactly like C/C++. I concatenated the arguments and then passed them to `os.system` as a single string.

`subprocess.call` takes a list of arguments. not a single string. it behaves a lot like `child_process.spawn`, not `os.system`. so when you changed it from `system` to `call`, it affected the way the arguments are processed.

piping output or input is typically a command line utility feature which is why i constructed it with `os.system` and not `subprocess.call`.

`cplib.set_command` does the work of translating the `namespace` to a single `list`.

luckily, you don't really have to change too much. `parse.Parser` would just need a small tweak to compensate for any changes since it manages the `sys.argv` parsing.

aside from that, you have to figure out how to grab the output and either write it to a file or figure out how use `call` to pipe it for you considering it has `stdin`, `stdout`, and `stderr` parameters.

the easiest way to grab the output from the executed process would be to execute `subprocess.check_output` in place of `call`.
source: [subprocess.check_output](https://docs.python.org/2/library/subprocess.html#subprocess.check_output)

Considering the implications it might be best to just use `popen` instead of `call` or `check_output`.
source: [subprocess.Popen](https://docs.python.org/2/library/subprocess.html#popen-constructor)

i'm sick right now, so i can barely focus on anything. when i'm feeling better, i might take a closer look.

**Comment by xovertheyearsx** [comment]
I'm really bored from just laying around from being sick, so I dug in to it and found a fairly simple way to do it.

first off, we can keep `subprocess.call`. leave `shell=False` as is. it's a security risk otherwise. technically this entire plugin is a security risk; however, that's another discussion for another time.

we'll need to tweak `cp.parse` so that it doesn't look for a pipe symbol anymore; rather it looks for what you suggested. `-s` for `stdout`, `-a` for append `stdout`, and `-e` for `stdout` and `stderr` or something along those lines. however, we still need to ask for a path and filename to write to.

so instead of using

`-p 'output.txt' '>' python {file}`

we can just do this instead

`-s '/path/to/output.txt' python {file}`

when piping is true, we can open a file under the given path and filename.

```
if namespace.pipe is True:
    with open(filename, 'w') as f:
        call(command, stdout=f, stderr=f)
        f.close
```

it will then write `stdout` and `stderr` to the given filename.

the code i used to test this was in my Windows Subsystem for Linux (WSL) on Win 10.

list directory contents
```
$ ls -l
total 9
drwxrwxrwx 0 th3ros th3ros 4096 Jul 25 18:43 bin
drwxrwxrwx 0 th3ros th3ros 4096 Jul 25 18:41 documents
-rw-rw-rw- 1 th3ros th3ros  123 Jul 31 21:49 example.log
-rwxrwxrwx 1 th3ros th3ros  534 Jul 25 18:45 setup.sh
lrwxrwxrwx 1 th3ros th3ros   19 Jul 27 21:41 windows -> /mnt/c/Users/Austin
```

concatenate example.log to stdout
```
$ cat example.log
DEBUG:root:Debug: This message should go to the log file
INFO:root:Info: So should this
WARNING:root:Warning: And this too
```

enter `python` and test and compare `subprocess.call` output to previous output
```
$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.call(['ls', '-l'])
total 9
drwxrwxrwx 0 th3ros th3ros 4096 Jul 25 18:43 bin
drwxrwxrwx 0 th3ros th3ros 4096 Jul 25 18:41 documents
-rw-rw-rw- 1 th3ros th3ros  123 Jul 31 21:49 example.log
-rwxrwxrwx 1 th3ros th3ros  534 Jul 25 18:45 setup.sh
lrwxrwxrwx 1 th3ros th3ros   19 Jul 27 21:41 windows -> /mnt/c/Users/Austin
0
>>> subprocess.call(['cat', 'example.log'])
DEBUG:root:Debug: This message should go to the log file
INFO:root:Info: So should this
WARNING:root:Warning: And this too
0
```

we can see the output is the same. the 0 at the end is just `call`'s return code. 

now, this is where things get interesting. 

we need a file to write to first. and then we need to write (or pipe) the output to that file.
```
>>> f = open('example.txt', 'w')
>>> f
<open file 'example.txt', mode 'w' at 0x7fff2100f660>
>>> subprocess.call(['ls','-l'], stdout=f)
0
>>> f.close()
>>> f
<closed file 'example.txt', mode 'w' at 0x7fff2100f660>
>>> subprocess.call(['cat','example.txt'])
total 9
drwxrwxrwx 0 th3ros th3ros 4096 Jul 25 18:43 bin
drwxrwxrwx 0 th3ros th3ros 4096 Jul 25 18:41 documents
-rw-rw-rw- 1 th3ros th3ros  123 Jul 31 21:49 example.log
-rw-rw-rw- 1 th3ros th3ros    0 Aug 10 16:25 example.txt
-rwxrwxrwx 1 th3ros th3ros  534 Jul 25 18:45 setup.sh
lrwxrwxrwx 1 th3ros th3ros   19 Jul 27 21:41 windows -> /mnt/c/Users/Austin
0
>>>
```

as you can see, it does pretty much what we would expect. all we have to do is implement this behavior. 

i have a date with some saline solution, soup, and my bed; so i'll catch you later.

**Comment by foreshadow** [comment]
It's ok, we can stop for a while, wish you getting better soon.

**Comment by xovertheyearsx** [comment]
The patch has been pushed upstream and is now available. It should work as expected now with the `Prepare 0.9.2 release`.
