### ISSUE TITLE
Run when a non .py file is open

### ISSUE THREAD

**Issue by Siecje** [foreshadow/atom-python-run#40]
I'm working on a PyQt5 project and I am editing .qml files and I want to be able to hit `F5` to run the application while a .qml file is open.

I thought I could just hard code the file to run, so I replaced `{file}` with the .py file I want to run. But when I have a .qml file open and I press `F5` it says `File.qml is not a .py file, exit.`

**Comment by xovertheyearsx** [comment]
This has to do with the way atom-python-run and cp executable looks at file extensions. Even if you tweeked the code in atom-python-run.js to ignore it, cp would still catch the fact the *.py extension is missing. 

All non-python files will always fail to execute. Even though I had previous plans to fix this so that any arbitrary source could be executed as long as the required dependencies were in place and were available via the PATH variable, I never got around to it. TBH, I should have left the orginal cp the way it was. This can be easily remedied though.

Hopefully, once foreshadow gets some time, we can work on fixing this.

**Comment by foreshadow** [comment]
There are ready-made package to run arbitrary source code in terminal. I have no intention to make a second one. As the package name is atom-python-run, we can focus on dealing problem with running python source code.

Actually, this package was initially made for my personal use (run a single python file, learn and practice node.js). I didn't expect that it is used by so many people now.

As for the extension name problem, I plan to use an data-grammar filter in keymap config which is provided [here](https://github.com/foreshadow/atom-python-run/issues/24#issuecomment-291382807).

I am free these days. I started woking on the new version.

**Comment by Siecje** [comment]
Sorry I don't understand these comments. I have made the changes locally and it is working for me.

https://github.com/foreshadow/atom-python-run/pull/41

**Comment by xovertheyearsx** [comment]
this should be all set now with the new update.
