### ISSUE TITLE
Able to run on windows but can't run on mac

### ISSUE THREAD

**Issue by Phoehtaung** [foreshadow/atom-python-run#55]
INFO: Platform: darwin
INFO: Version Info: v0.2.0
DEBUG: Log Path: /Users/okarmin/.atom/packages/atom-python-run/cp.log
DEBUG: _ast: "['--pause', '/Users/okarmin/Google', 'Drive/v1.1/okarBot.py']"
DEBUG: Index: "0" Token: "--pause"
DEBUG: Index: "1" Token: "/Users/okarmin/Google"
DEBUG: Index: "2" Token: "Drive/v1.1/okarBot.py"
ERROR: Error: Expected optional option argument: got "Drive/v1.1/okarBot.py" instead

**Comment by xovertheyearsx** [comment]
whats `atom`s console log say?

**Comment by foreshadow** [comment]
@xovertheyearsx 
It seems that the path is splited by the space in `Google Drive`

**Comment by xovertheyearsx** [comment]
cant be sure until we see the console log. it also looks like no repl was passed. `cp` looks for a repl, options (which are split up in to list items), and then the script. the spacing in the path should not make a difference (although, it is possible). either way, all we can do is speculate until we see the console log; so we know for sure.

**Comment by Phoehtaung** [comment]
Console log says nothing much about atom-python-run.
I've replicated the error before cmd+alt+i

Here's all that console log shows me

<embedded>:118131 IntersectionObserver.observe(target): target element is not a descendant of root.
TreeView @ <embedded>:118131
<embedded>:119605 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
module.exports.TreeView.isVisible @ <embedded>:119605
<embedded>:1032 EACCES: permission denied, symlink '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/apm' -> '/usr/local/bin/apm'
(anonymous) @ <embedded>:1032
<embedded>:1027 EACCES: permission denied, symlink '/Applications/Atom.app/Contents/Resources/app/atom.sh' -> '/usr/local/bin/atom'
(anonymous) @ <embedded>:1027

**Comment by xovertheyearsx** [comment]
You can do it while the console is open.

Are you using default settings in the settings panel for the `atom-python-run` package? If not, what are they set to?

**Comment by Phoehtaung** [comment]
I've followed your instructions:

Using Default Settings

- Console Log option is off
- Console Window is open
- clear() in Console Log
- Replciated the issue
- Output of cp.log pasted below
- 

and screenshot attached for your reference

![atom-python-run](https://user-images.githubusercontent.com/24297303/31313767-2f4b581e-ac1f-11e7-9f2c-4afccd504dc1.png)

**Comment by xovertheyearsx** [comment]
that's why youre not getting a log; which is what we were looking for. you need to check it so its on to help us debug issues.

also, you need to pass a repl argument. you cant just call the file. it will fail because `cp` wont know how to execute the file otherwise.

restore it so that it says `python  {file}` instead of just `{file}` and it will work again.

if youre interested in using the `shebang` feature, you'll need to execute it normally as windows doesnt support this feature and is unix only.

**Comment by xovertheyearsx** [comment]
its important to note that systems calls are unique to each operating system. this means that this package behaves according to how the os handles a system call.

for example, setting the terminal and option in mac will break the call but will work just fine in windows and linux.

theres nothing this package can do to change that and it falls out of the scope of this package. the goal is to simply attach a system call to a command (or create a macro) key.

when you make a call, youre supposed to specifiy the program that makes that call, otherwise the machine wont know how to handle it. in the special case of the shebang, it will execute accordingly, but only on unix like systems. unfortunately, i disregarded including that because of any underlying complexity that might result from it. not only that, youre probably better off automating that call some other way; if that is the goal.

hope this clears up any confusion.
