### ISSUE TITLE
Parameters passing

### ISSUE THREAD

**Issue by YuriPetrov** [foreshadow/atom-python-run#62]
Hi, 

i'm trying to pass params to a script (set on F6 button):
`python check.py {file}`

so that Python can open my script ``check.py`` with `{file}` parameter. Unfortunately, this command only runs `check.py` with no parameters received, How can I do it?

**Comment by xovertheyearsx** [comment]
you can't. there's no current method for adding and/or passing arguments to a script. the executed script must **always** be the last argument. maybe sometime in the future we can fix this, or if you want, look at the source code, change it, and make a pull request.

**Comment by foreshadow** [comment]
@xovertheyearsx 
So what is the technical reason that it is not supported now? I suppose `cp` can handle any arguments.

**Comment by xovertheyearsx** [comment]
i'm caught up in some other stuff, but it's actually just the way `cp` is implemented. at the time, i thought some restrictions would be good to have (security reasons). that's why '_these issues_' keep cropping up.

the format cp is designed to take is

`repl [options... [args...]] {file}`

where the last arg, `{file}`, **must always** be a file.

I should have just used `argparse` and used `-` as the option termination symbol. it'd be quicker to write up, easier to maintain, and allow people do what they expect.

for example

`repl [options...] [args...]`

would work much better. 

you could just rewrite the `lexer.py` and make sure it interfaces with `argparse`s results. I realized this when I drafted the docs for the wiki.

looking back at it now, it was obviously a bad idea. i'm just caught up setting up my current work station. i was planning on fixing it soon, other wise i could just rewrite it in no time at all. unless you're up to the task.

You don't even have to read `lexer.py`. You have to trash it because of the way `argparse` works. `parser.py` uses the the tokens and should need minimal tweaking along with `main.py`. Other than that, it should work fine.

It's layered as

1. utils.py
2. fnp.py (deprecate)
3. lexer.py (refactor to use argparse)
4. parser.py (minimal tweaking to ensure tokens are interpreted correctly)
5. main.py (same as step 4)
6. terminal.js (Make a few adjustments so it calls `cp` the right way)
7. atom-python-run.js (should not need any changes)

I broke the golden rule by not keeping it simple (_kiss_).

If not, it may be a few days until I can get to it. At least until my system is ready for dev.
