### ISSUE TITLE
Atom-python-run  0.9.5 

### ISSUE THREAD

**Issue by Brave731** [foreshadow/atom-python-run#66]
I'm update the package today, find this error!!!
BufferExceptionTypeError: Cannot read property 'then' of undefined: You failed to create the file before attempting to execute it.

**Comment by foreshadow** [comment]
IIRC, This error reminds you to create the file first. @xovertheyearsx
I think we can make this notification more simpler to understand.

**Comment by Brave731** [comment]
I use the old version(8.0) without this problem.

**Comment by xovertheyearsx** [comment]
@foreshadow The thought occurred to me **after** I had made the commit. I figured if we did see something, it would look like this. Which is why I didn't just tell it to `return undefined`. Maybe we should allow the uncaught exeception? Make the error message adapt to the situation instead of explicitly assuming the file had not been saved? How should we handle this?

@Brave731 Can you give more information on what you're doing.

- Did you save the file before executing? (this has to do with atom more than the plugin).

If you did save the file, you should provide the logs that `atom-python-run` creates.

- There is the atom console log and then the atom-python-run log.
- If these logs are created, I'd assume that only the atom console log would log anything at all.

If you did not save the file, you are **required** to save it **before** execution. It's required by Atom, the text editor, not the plugin. Atom will generate an exception regardless.

**Comment by xovertheyearsx** [comment]
@foreshadow After a quick google search, the `TypeError` seems to be generated because I failed to return the promise. TBH, [this](https://github.com/foreshadow/atom-python-run/blob/5862a3d63a248242066bbcac6e171075022e22be/lib/atom-python-run.js#L27) is a weird one. So if the exception occurs, it still expects a promise? And if so, a promise of what? The promise failed.

These are some SO posts I found online:
[Promise TypeError](https://stackoverflow.com/questions/26151312/promise-typeerror-cannot-read-property-then-of-undefined)
[Missing TypeError](https://stackoverflow.com/questions/24788171/typeerror-cannot-read-property-then-of-undefined#24788320)

**Comment by Brave731** [comment]
@xovertheyearsx Thank you for your reply. I do not understand what you mean by creating a file(not save). when I use the version 0.8.0 without this problem, two versions has different operations?
Note: the atom-python-run log is empty.
now, I've been back to version 0.8, everything is right.

**Comment by xovertheyearsx** [comment]
@Brave731 When the file does not exist, you have to create it so that it does exist. You can consider it being equal to your first `save as`. 

For example, when you "new file" in atom, you create a buffer, not a file. The buffer is where all the data is kept to keep track of your data. In this case, the data is most likely source code.

The file does not exist until you "save as" and give the file a name (or identifier). When you do this, it copies the buffer to the file and writes it to disk so that you can open it again later.

You can't execute the buffer, but you can pass the file along to be executed, which is what atom-python-run does. When the file doesn't exist, you're attempting to execute the data residing in the buffer and not in a file. That's when the exception occurs.

Honestly, my best guess is so that malicious code can't be injected in to or directly executed through memory. Typically known as a buffer overflow. I just know that if it doesn't exist first, you run in to problems like this. I can't assume that was your problem because your error doesn't reflect that issue (that i know of), although, I wouldn't be surprised if it was related.

I wrote a patch that catches that exception because of a similiar issue recently posted. Your error is what came out of it. Everything else pretty much works the same.

**Comment by Brave731** [comment]
I found the problem is the atom version, updated the atom version, and then it works.
@xovertheyearsx  When you update a new version, can set the atom version requirements.

**Comment by foreshadow** [comment]
Fixed in v0.9.6, supports both old(<v.1.19) and new(>=v1.19) versions of atom.
