### ISSUE TITLE
TerminalError

### ISSUE THREAD

**Issue by Fahim-Ferdous** [foreshadow/atom-python-run#68]
Hi there, I have a new fresh Linux Mint installation but when I press f5 or f6, atom gives me a TerminalError and suggests to install gnome-terminal. But I already have it and it is working fine. Only atom is unable to execute...

**Comment by xovertheyearsx** [comment]
logs help alot when troubleshooting. you can check atoms built-in `console` log and check to see if there is a `cp.log` file within the `~/.atom/packages/atom-python-run` directory. in this context, the built-in log will provide a better picture of what's happening.

go to `settings` -> `packages` -> `atom-python-run` -> `settings`

make sure that the `Console Log` option is checked and active. 

`ctrl + shift + i` and click on `console` and reproduce what ever you were trying to do. a simple hello world test works fine for this. create, save, and execute with `F5`.

copy and paste the log output.

if it fails to execute, go to the `Terminal` field and type in `gnome-terminal, -x` and see if it works.

if it fails, and still doesn't work, make sure it is installed.

```
$ which gnome-terminal
/usr/bin/gnome-terminal
```

If there is no output from the `which` command, it is NOT installed. you'll have to install the applet to remedy the situation.

it could also be because of an environment variable i wasn't aware of. you can always check to see what that variable is and report that information as well.

```
$ printenv | grep -i 'gnome'
XDG_MENU_PREFIX=gnome-
DESKTOP_SESSION=gnome
XDG_SESSION_DESKTOP=gnome
XDG_CURRENT_DESKTOP=GNOME
GDMSESSION=gnome
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
```

In your case, it might be more appropriate to just do `printenv | grep -i 'cinnamon'` since that is mints default desktop environment.

**Comment by Fahim-Ferdous** [comment]
Hi there, The console log option was turned on and still is. But there is no output file or even .atom directory.
And the following came out of `printenv | grep -i 'cinnamon'`
DEFAULTS_PATH=/usr/share/gconf/cinnamon.default.path
XDG_CONFIG_DIRS=/etc/xdg/xdg-cinnamon:/etc/xdg
DESKTOP_SESSION=cinnamon
MANDATORY_PATH=/usr/share/gconf/cinnamon.mandatory.path
GDMSESSION=cinnamon
XDG_SESSION_DESKTOP=cinnamon
XDG_DATA_DIRS=/usr/share/cinnamon:/usr/share/gnome:/home/fahim/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_CURRENT_DESKTOP=X-Cinnamon

**Comment by xovertheyearsx** [comment]
- reproduce the error and then follow the steps [here](https://github.com/foreshadow/atom-python-run#logs) for logs. 
- was there output for `which gnome-terminal`?
- did you test the `Terminal` setting in Settings?

The environment seems to be as expected.

**Comment by Fahim-Ferdous** [comment]
Hi there, The console log option was turned on and still is. But there is no output file or even .atom directory.
And the following came out of `printenv | grep -i 'cinnamon'`
DEFAULTS_PATH=/usr/share/gconf/cinnamon.default.path
XDG_CONFIG_DIRS=/etc/xdg/xdg-cinnamon:/etc/xdg
DESKTOP_SESSION=cinnamon
MANDATORY_PATH=/usr/share/gconf/cinnamon.mandatory.path
GDMSESSION=cinnamon
XDG_SESSION_DESKTOP=cinnamon
XDG_DATA_DIRS=/usr/share/cinnamon:/usr/share/gnome:/home/fahim/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_CURRENT_DESKTOP=X-Cinnamon

**Comment by xovertheyearsx** [comment]
Look [here](https://github.com/foreshadow/atom-python-run/wiki/12-How-Do-I-Use-atom-python-run#console-log) for help on how to access and use the Console Log. 

You can see [here](https://github.com/foreshadow/atom-python-run/wiki/12-How-Do-I-Use-atom-python-run#console-vs-cp-log) that the Console Log and cp Log are different logging mechanisms.

Feel free to express if you're confused and/or need additional clarification. If you've found a fix, please post it here, make a pull request, or create a fork with an implemented fix.
