### ISSUE TITLE
Terminal opening in background (Ubuntu 16)

### ISSUE THREAD

**Issue by FredhRodrigues** [foreshadow/atom-python-run#73]
Hello guys. I was using everything without a problem, then I don't know if I hit the wrong key or changed the wrong lines in config.cson but now this started to happen. At first I thought f5 was not working anymore then I saw a dozen terminal windows in the back. 

This is really annoying. Is there anyway to make it open in the foreground again? Thanks in advance.

**Comment by xovertheyearsx** [comment]
@FredhRodrigues -- [README](https://github.com/foreshadow/atom-python-run/wiki/00-Readme) -- #69 

### **Terminal opening in background (Ubuntu 16) #73**  

> Hello guys. I was using everything without a problem, then I don't know if I hit the wrong key or changed the wrong lines in config.cson but now this started to happen. At first I thought f5 was not working anymore then I saw a dozen terminal windows in the back.
> 
> This is really annoying. Is there anyway to make it open in the foreground again? Thanks in advance.

Even though issue #73 takes place in Ubuntu 16.xx, which I find interesting because it uses Unity as its WM and DE, it can be cataloged here since it resembles this issue, #70. Issue #73 will be merged with issue #70 to help isolate this general issue.
