### ISSUE TITLE
Running 2 versions of python

### ISSUE THREAD

**Issue by Vulcannn** [foreshadow/atom-python-run#74]
I use python 3.5 and 3.6 both regularly for different reasons. Although python3.6 seems to take over 3.5 when running a file. I tried to set it so it would run on 3.5 using f5 and 3.6 using f6. Although it would just run 3.6

This is what I tried 
![image](https://user-images.githubusercontent.com/26766043/36551504-9d580ac8-17ef-11e8-8386-f47f3759d846.png)

I was wondering if it would be possible to set which version of python it used or if there is a correct way of defining which version to use. Thanks

**Comment by xovertheyearsx** [comment]
I updated the [wiki](https://github.com/foreshadow/atom-python-run/wiki/) to showcase how the [Command Fields](https://github.com/foreshadow/atom-python-run/wiki/12-How-Do-I-Use-atom-python-run#commands) work in fair amount of detail. You can always use google (or your preferred search provider) to look up how to properly set up the PATH environment variable if that turns out to be your issue.
